swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:

  # -------Form---------
  /form:
    x-swagger-router-controller: form.controller
    get:
      description: Gets all forms
      operationId: getAllForms
      tags:
        - Form
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Form'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      description: Creates a form
      operationId: createForm
      tags:
        - Form
      parameters:
        - name: subject
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              link:
                type: string
              tags:
                type: array
                items:
                  type: string
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/Form'
        default:
          description: Error
          schema:
            type: object
            properties:
              form:
                type: string
              text:
                type: string
              priority:
                type: number

    put:
      description: Modify form
      operationId: modifyForm
      tags:
        - Form
      responses:
        200:
          description: OK

  # -------Question---------
  /form/question/{formId}:
    x-swagger-router-controller: question.controller
    post:
      description: Creates question on a form
      tags:
        - Question
      operationId: createQuestion
      parameters:
        - in: path
          name: formId
          type: string
          required: true
        - in: body
          name: question
          schema:
            $ref: '#/definitions/Question'
      responses:
        "200":
          description: Question created
          schema:
            $ref: '#/definitions/Question'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'

    get:
      description: Get all questions per form
      tags:
        - Question
      operationId: getQuestionsForForm
      parameters:
        - in: path
          name: formId
          type: string
          required: true
      responses:
        "200":
          description: Question created
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /question/{questionId}:
    x-swagger-router-controller: question.controller
    delete:
      description: Deletes a question
      operationId: deleteQuestion
      tags:
        - Question
      parameters:
        - in: path
          name: questionId
          type: string
          required: true
      responses:
        200:
          description: OK

  /question:
    x-swagger-router-controller: question.controller
    put:
      description: Modify questions
      operationId: modifyQuestions
      tags:
        - Question
      parameters:
        - in: body
          name: questions
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
      responses:
        "200":
          description: Question created
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'

  /swagger:
    x-swagger-pipe: swagger_raw

# -------Models---------
definitions:
  Form:
    type: object
    description: This is represents a form
    properties:
      _id:
        type: string
      name:
        type: string
      link:
        type: string
      tags:
        type: array
        items:
          type: string

  Question:
    type: object
    description: This is represents a question
    properties:
      _id:
        type: string
      form:
        type: string
      text:
        type: string
      priority:
        type: number

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
